name: handwriting_recognition_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
    - mlflow>=2.4.0
    - tensorflow>=2.9.0
    - numpy>=1.21.0
    - matplotlib>=3.5.0
    - pillow>=9.0.0
    - flask>=2.0.0